//
//  MessageModels.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol GenericMessage {
    var message: String { get set }
    var sender: String { get set }
}

enum Message
{
    enum MessageType {
        case schedule
        case payment
        case message
        case image
        
    }
    
    struct Message: GenericMessage {
        var message: String
        
        var sender: String

    }
    struct ImageMessage: GenericMessage {
        var message: String
        var sender: String
        var image: UIImage?
    }
    struct QuoteMessage: GenericMessage {
        var message: String
        var sender: String
        var quotePrice: Double
        var quoteDescription: String = ""
        var messageID: String
    }
    struct ScheduleMessage: GenericMessage {
        var message: String
        var sender: String
        
        struct Appointment {
            var datetime: Date
            
        }
        var duration: Int
        var title: String
        var availabilities: [Double]
        
    }
    // MARK: Use cases
    
    enum FetchMessages
    {
        struct Request
        {
        }
        struct Response
        {
            var userName: String
            var businessName: String
            var messages: [GenericMessage]
        }
        struct ViewModel
        {
            var userName: String
            var businessName: String
            var messages: [GenericMessage]
        }
    }
    enum SendQuote {
        struct Request
        {
            var message: QuoteMessage
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum SendSchedule {
        struct Request
        {
            var message: ScheduleMessage
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum SendMessage
    {
        struct Request
        {
            var message: Message
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    enum SendImage
    {
        struct Request
        {
            var info: [String : Any]
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
