//
//  MessagePresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MessagePresentationLogic
{
    func presentMessages(response: Message.FetchMessages.Response)
}

class MessagePresenter: MessagePresentationLogic
{
    weak var viewController: MessageDisplayLogic?
    
    // MARK: Do something
    
    func presentMessages(response: Message.FetchMessages.Response) {
        let msgs = response.messages
//        let msgs = response.messages.filter { (m) -> Bool in
//            m.sender == "contractor" || m.sender == response.
//
//
//        }
        self.viewController?.displayMessages(vm: Message.FetchMessages.ViewModel(userName: response.userName, businessName: response.businessName, messages: msgs))
    }
}
