//
//  ShowInboxRouter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowInboxRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToShowMessages(segue: UIStoryboardSegue)
}

protocol ShowInboxDataPassing
{
  var dataStore: ShowInboxDataStore? { get }
}

class ShowInboxRouter: NSObject, ShowInboxRoutingLogic, ShowInboxDataPassing
{
  weak var viewController: ShowInboxViewController?
  var dataStore: ShowInboxDataStore?
  
  // MARK: Routing
    
    func routeToShowMessages(segue: UIStoryboardSegue) {
        let destinationVC = segue.destination as! MessageViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToListProjects(source: dataStore!, destination: &destinationDS)
        
    }
    func passDataToListProjects(source: ShowInboxDataStore, destination: inout MessageDataStore)
    {
        let row = (self.viewController?.inboxTableView.indexPathForSelectedRow?.row)!
        
        destination.conversation = source.conversations[row]
        
    }
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ShowInboxViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ShowInboxDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
