//
//  ShowInboxInteractor.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowInboxBusinessLogic
{
    func fetchInbox()
}

protocol ShowInboxDataStore
{
    //var name: String { get set }
    var conversations: [Conversation]! { get set }
}

class ShowInboxInteractor: ShowInboxBusinessLogic, ShowInboxDataStore
{
    var presenter: ShowInboxPresentationLogic?
    var worker: ShowInboxWorker?
    var conversations: [Conversation]!
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchInbox() {
        self.conversations =  MessengerWorker.sharedInstance.conversations
        let resp = ShowInbox.FetchInbox.Response(conversations: conversations)
        self.presenter?.presentInbox(response: resp)
    }
    
    
}
