//
//  ShowInboxPresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowInboxPresentationLogic
{
    func presentInbox(response: ShowInbox.FetchInbox.Response)
}

class ShowInboxPresenter: ShowInboxPresentationLogic
{
    weak var viewController: ShowInboxDisplayLogic?
    
    // MARK: Do something
    
    func presentInbox(response: ShowInbox.FetchInbox.Response) {
        var tempArr: [ShowInbox.FetchInbox.ViewModel.DisplayableConversation] = []
        for each in response.conversations {
            let disp = ShowInbox.FetchInbox.ViewModel.DisplayableConversation(businessName: each.name, message: "", time: "")
            tempArr.append(disp)
        }
        self.viewController?.displayInbox(viewModel: ShowInbox.FetchInbox.ViewModel(conversations: tempArr))
    }
}
