//
//  PaymentViewController.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 12/15/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Stripe
import Eureka

protocol PaymentDisplayLogic: class
{
    func displaySomething(viewModel: Payment.Something.ViewModel)
}

class PaymentViewController: FormViewController, PaymentDisplayLogic
{
    var interactor: PaymentBusinessLogic?
    var router: (NSObjectProtocol & PaymentRoutingLogic & PaymentDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = PaymentInteractor()
        let presenter = PaymentPresenter()
        let router = PaymentRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        form +++ Section("Card Information")
            <<< IntRow(){ row in
                row.title = "Card Number"
                row.placeholder = "Enter Number Here"
            }
            <<< DateRow(){
                $0.title = "Expiration Date"
                $0.value = Date()
            }
            <<< IntRow(){
                $0.title = "CVV"
                $0.placeholder = "Enter Here"
            }
            +++ Section("Personal Information")
            <<< TextRow(){
                $0.title = "Full Name"
                $0.placeholder = "Full Name Here"
            }
            <<< TextRow(){
                $0.title = "Street"
                $0.placeholder = "123 Infinity Loop"
            }
            <<< TextRow(){
                $0.title = "City"
                $0.placeholder = "Pittsburgh"
            }
            <<< TextRow(){
                $0.title = "State"
                $0.placeholder = "PA"
            }
            <<< ZipCodeRow(){
                $0.title = "Zip Code"
                $0.placeholder = "12345"
        }
    }
    @IBAction func close() {
        self.navigationController?.popViewController(animated: true)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = Payment.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Payment.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}

//extension PaymentViewController: STPPaymentContextDelegate {
//
//    func paymentContextDidChange(_ paymentContext: STPPaymentContext) {
//
//    }
//    func paymentContext(_ paymentContext: STPPaymentContext, didCreatePaymentResult paymentResult: STPPaymentResult, completion: @escaping STPErrorBlock) {
//
//    }
//    func paymentContext(_ paymentContext: STPPaymentContext, didFinishWith status: STPPaymentStatus, error: Error?) {
//
//    }
//    func paymentContext(_ paymentContext: STPPaymentContext, didFailToLoadWithError error: Error) {
//
//    }
//
//
//}














