//
//  HomeInteractor.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/8/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func fetchCategories()
}

protocol HomeDataStore
{
    //var name: String { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker = HomeWorker()
    //var name: String = ""
    
    // MARK: Do something
    func fetchCategories() {
        worker.fetchCategorie { (data) in
            self.presenter?.presentCategories(response: Home.FetchCategories.Response(data: data))
        }
    }
    
}
