//
//  HomeWorker.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/8/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    let service = BusinessTester()
    
    func fetchCategorie(completion: @escaping ([(String, Int, UIImage)]) -> Void) {
        let data = self.service.generateForCategories()
        var temp: [(String, Int, UIImage)] = []
        for (key, (img, businesses)) in data {
            let a = (key, businesses.count, img)
            temp.append(a)
        }
        completion(temp)
        
    }
}
