//
//  SignInPresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/15/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInPresentationLogic
{
  func presentSomething(response: SignIn.Something.Response)
}

class SignInPresenter: SignInPresentationLogic
{
  weak var viewController: SignInDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn.Something.Response)
  {
    let viewModel = SignIn.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
