//
//  SignInWorker.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/15/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SignInWorker
{
    func doSomeWork()
    {
    }
}
