//
//  ShowProfileModels.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/8/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowProfile
{
    // MARK: Use cases
    
    enum FetchUser
    {
        struct Request
        {
        }
        struct Response
        {
            var name: String
        }
        struct ViewModel
        {
            var name: String
        }
    }
}
