//
//  ShowProfileViewController.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/8/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseAuth
import GoogleSignIn

protocol ShowProfileDisplayLogic: class
{
//    func displaySomething(viewModel: ShowProfile.Something.ViewModel)
    func displayProfile(vm: ShowProfile.FetchUser.ViewModel)
}

class ShowProfileViewController: UIViewController, ShowProfileDisplayLogic
{
    var interactor: ShowProfileBusinessLogic?
    var router: (NSObjectProtocol & ShowProfileRoutingLogic & ShowProfileDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ShowProfileInteractor()
        let presenter = ShowProfilePresenter()
        let router = ShowProfileRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.navigationController?.clearShadow()
        self.interactor?.fetchUser()
    }
    func fetchProfile() {
        
    }
    func displayProfile(vm: ShowProfile.FetchUser.ViewModel) {
        self.profileImage.image = vm.image
        self.nameLabel.text = vm.name
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var profileImage: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    
    
    @IBAction func signOut(_ sender: UIButton) {
        let firebaseAuth = Auth.auth()
        do {
            try firebaseAuth.signOut()
            dismiss(animated: true, completion: nil)
        } catch let signOutError as NSError {
            print ("Error signing out: \(signOutError.localizedDescription)")
        }
    }
//    func doSomething()
//    {
//        let request = ShowProfile.Something.Request()
//        interactor?.doSomething(request: request)
//    }
//
//    func displaySomething(viewModel: ShowProfile.Something.ViewModel)
//    {
//        //nameTextField.text = viewModel.name
//    }
}
