//
//  ShowProfileInteractor.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/8/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowProfileBusinessLogic
{
  func doSomething(request: ShowProfile.Something.Request)
}

protocol ShowProfileDataStore
{
  //var name: String { get set }
}

class ShowProfileInteractor: ShowProfileBusinessLogic, ShowProfileDataStore
{
  var presenter: ShowProfilePresentationLogic?
  var worker: ShowProfileWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowProfile.Something.Request)
  {
    worker = ShowProfileWorker()
    worker?.doSomeWork()
    
    let response = ShowProfile.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
