//
//  ShowProfilePresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 11/8/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowProfilePresentationLogic
{
//  func presentSomething(response: ShowProfile.Something.Response)
    func presentProfile(response: ShowProfile.FetchUser.Response)
}

class ShowProfilePresenter: ShowProfilePresentationLogic
{
  weak var viewController: ShowProfileDisplayLogic?
  
  // MARK: Do something
    func presentProfile(response: ShowProfile.FetchUser.Response) {
        self.viewController?.displayProfile(vm: ShowProfile.FetchUser.ViewModel(name: response.name, image: response.image))
    }
  
}
