//
//  ShowBusinessesModels.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowBusinesses
{
  // MARK: Use cases
  
  enum FetchBusiness
  {
    struct Request
    {
    }
    struct Response
    {
        var business: Business
    }
    struct ViewModel
    {
//        struct DisplayableBusiness {
//            var name: String
//            var businessType: String
//            var image: UIImage
//        }
        var name: String
        var businessType: String
        var image: UIImage
        var phone: String
        var website: String
        
        var reviewCount: String
        
        struct DisplayableReview {
            var name: String
            var img: UIImage
            var review: String
            var rating: String
        }
        var reviews: [DisplayableReview]
    }
  }
}
