//
//  ShowBusinessesPresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol ShowBusinessesPresentationLogic
{
    func presentBusiness(response: ShowBusinesses.FetchBusiness.Response)
}

class ShowBusinessesPresenter: ShowBusinessesPresentationLogic
{
    weak var viewController: ShowBusinessesDisplayLogic?
    
    // MARK: Do something
    
    func presentBusiness(response: ShowBusinesses.FetchBusiness.Response) {
        var reviews: [ShowBusinesses.FetchBusiness.ViewModel.DisplayableReview] = []
        for r in response.business.reviews {
            let rev = ShowBusinesses.FetchBusiness.ViewModel.DisplayableReview(name: r.username, img: #imageLiteral(resourceName: "placeholder"), review: r.detail, rating: r.rating)
            reviews.append(rev)
        }
//        for i in 0...3 {
//            let review = ShowBusinesses.FetchBusiness.ViewModel.DisplayableReview(name: "Jenna Dean", img: #imageLiteral(resourceName: "person1"), review: "Jack is very skilled and always gets the job done right. Make sure you schedule in advance!")
//            reviews.append(review)
//        }
        let count = response.business.reviewCount
        let vm = ShowBusinesses.FetchBusiness.ViewModel(name: response.business.name, businessType: response.business.businessType[0].displayName, image: response.business.images.first ?? #imageLiteral(resourceName: "placeholder"), phone: response.business.phone, website: response.business.yelpURL, reviewCount: "\(count)", reviews: reviews)
        self.viewController?.displayBusiness(viewModel: vm)
    }
}
