//
//  ShowBusinessesInteractor.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import AlamofireImage

protocol ShowBusinessesBusinessLogic
{
    func fetchBusiness() 
}

protocol ShowBusinessesDataStore
{
    var business: Business! { get set }
}

class ShowBusinessesInteractor: ShowBusinessesBusinessLogic, ShowBusinessesDataStore
{
    var presenter: ShowBusinessesPresentationLogic?
    var worker = YelpWorker()
    var business: Business!
    
    // MARK: Do something
    
    func fetchBusiness() {
        worker.getBusiness(business: self.business) { (b) in
            self.business = b
            let imgURL = self.business.heroImageURL
            if self.business.images.count == 0 {
                Alamofire.request(imgURL).responseImage(completionHandler: { (response) in
                    if let image = response.result.value {
                        print("whaaa")
                        self.business.images.append(image)
                        self.presenter?.presentBusiness(response: ShowBusinesses.FetchBusiness.Response(business: self.business))
                    } else {
                        self.presenter?.presentBusiness(response: ShowBusinesses.FetchBusiness.Response(business: self.business))
                    }
                })
            } else {
                self.presenter?.presentBusiness(response: ShowBusinesses.FetchBusiness.Response(business: self.business))
            }
            self.worker.reviews(business: self.business, completion: { (b) in
                self.business = b
                self.presenter?.presentBusiness(response: ShowBusinesses.FetchBusiness.Response(business: self.business))
            })
            
            
        }
        
    }
}
