//
//  ShowBusinessesRouter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowBusinessesRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToListProjects(segue: UIStoryboardSegue)
    func routeToAddProject(segue: UIStoryboardSegue)
}

protocol ShowBusinessesDataPassing
{
  var dataStore: ShowBusinessesDataStore? { get }
}

class ShowBusinessesRouter: NSObject, ShowBusinessesRoutingLogic, ShowBusinessesDataPassing
{
  weak var viewController: ShowBusinessesViewController?
  var dataStore: ShowBusinessesDataStore?
  
  // MARK: Routing
    func routeToListProjects(segue: UIStoryboardSegue) {
        let destinationVC = ((segue.destination as! UINavigationController).viewControllers.first!) as! ListProjectsViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToListProjects(source: dataStore!, destination: &destinationDS)

    }
    func passDataToListProjects(source: ShowBusinessesDataStore, destination: inout ListProjectsDataStore)
    {
        destination.doSelect = true
        
    }
    func routeToAddProject(segue: UIStoryboardSegue) {
        let destinationVC = segue.destination  as! AddProjectViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToAddProject(source: dataStore!, destination: &destinationDS)
    }
    func passDataToAddProject(source: ShowBusinessesDataStore, destination: inout AddProjectDataStore)
    {
        destination.business = source.business
        
        
    }

  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
//      let destinationVC = segue.destination as! SomewhereViewController
//      var destinationDS = destinationVC.router!.dataStore!
//      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ShowBusinessesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: ShowBusinessesDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
}
