//
//  ShowBusinessesInteractor.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowBusinessesBusinessLogic
{
    func fetchBusiness() 
}

protocol ShowBusinessesDataStore
{
    var business: Business! { get set }
}

class ShowBusinessesInteractor: ShowBusinessesBusinessLogic, ShowBusinessesDataStore
{
    var presenter: ShowBusinessesPresentationLogic?
    var worker: ShowBusinessesWorker?
    var business: Business!
    
    // MARK: Do something
    
    func fetchBusiness() {
        self.presenter?.presentBusiness(response: ShowBusinesses.FetchBusiness.Response(business: self.business))
    }
}
