//
//  AddMultimediaInteractor.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddMultimediaBusinessLogic
{
    func addPhoto(request: AddMultimedia.AddPhoto.Request)
}

protocol AddMultimediaDataStore
{
    //var name: String { get set }
    var imageIndex: Int { get set }
}

class AddMultimediaInteractor: AddMultimediaBusinessLogic, AddMultimediaDataStore
{
    var presenter: AddMultimediaPresentationLogic?
    var worker: AddMultimediaWorker?
    var projectWorker = ProjectWorker.sharedInstance
    //var name: String = ""
    var imageIndex: Int = 0
    
    // MARK: Do something
    
    func addPhoto(request: AddMultimedia.AddPhoto.Request) {
        let img = request.image
        if imageIndex >= self.projectWorker.images.count {
            self.projectWorker.images.append(img)
        } else {
            self.projectWorker.images[imageIndex] = img
        }
        self.presenter?.presentAddPhoto()
        
        
    }
}
