//
//  AddProjectModels.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddProject
{
    // MARK: Use cases
    
    enum FetchPhotos
    {
        struct Request
        {
        }
        struct Response
        {
            var images: [UIImage]
        }
        struct ViewModel
        {
            var images: [UIImage]
        }
    }
    enum AddProject {
        struct Request
        {
            var name: String
            var jobType: String
            var details: String
            
        }
        struct Response
        {
            
        }
        struct ViewModel
        {
            
        }
    }
    enum FetchProject {
        struct Request
        {
            
            
        }
        struct Response
        {
            var project: Project
        }
        struct ViewModel
        {
            var name: String
            var jobType: String
            var details: String
            var images: [UIImage]
        }
    }
}
