//
//  AddProjectPresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddProjectPresentationLogic
{
    func presentPhotos(response: AddProject.FetchPhotos.Response)
    func presentProject(response: AddProject.FetchProject.Response)
}

class AddProjectPresenter: AddProjectPresentationLogic
{
    weak var viewController: AddProjectDisplayLogic?
    
    // MARK: Do something
    
    func presentPhotos(response: AddProject.FetchPhotos.Response) {
        self.viewController?.displayPhotos(viewModel: AddProject.FetchPhotos.ViewModel(images: response.images))
    }
    func presentProject(response: AddProject.FetchProject.Response) {
        let vm = AddProject.FetchProject.ViewModel(name: response.project.name, jobType: response.project.jobType, details: response.project.detail, images: response.project.images)
        self.viewController?.displayProject(viewModel: vm)
    }
}

