//
//  MessengerWorker.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class Conversation {
    
//    var business: Business
//    var project: Project
    var name: String
    var yelpID: String
    var image: UIImage?
    var conversationID: String
    var projectName: String = ""
    var contractorID: String
    
    
    init(name: String, convoID: String, yelpID: String, _ img: UIImage? = nil, cID: String) {
        self.name = name
        
        self.yelpID = yelpID
        self.conversationID = convoID
        self.contractorID = cID
//        self.project = proj
    }
    
}

class MessengerWorker
{
    static let sharedInstance = MessengerWorker()
    
    var conversations: [Conversation] = []
    
}
