//
//  ListProjectsRouter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListProjectsRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToShowProject(segue: UIStoryboardSegue)
}

protocol ListProjectsDataPassing
{
    var dataStore: ListProjectsDataStore? { get }
}

class ListProjectsRouter: NSObject, ListProjectsRoutingLogic, ListProjectsDataPassing
{
    weak var viewController: ListProjectsViewController?
    var dataStore: ListProjectsDataStore?
    
    // MARK: Routing
    
    func routeToShowProject(segue: UIStoryboardSegue)
    {
        
        
        let destinationVC = segue.destination as! AddProjectViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToShowProject(source: dataStore!, destination: &destinationDS)
    }
    func passDataToShowProject(source: ListProjectsDataStore, destination: inout AddProjectDataStore) {
        let proj: Project? = viewController?.projects[viewController!.projectsTableView.indexPathForSelectedRow!.row]
        destination.project = proj
        
    }
//    func routeToSomewhere(segue: UIStoryboardSegue?)
//    {
//      if let segue = segue {
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: ListProjectsViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: ListProjectsDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
