//
//  ListProjectsModels.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListProjects
{
  // MARK: Use cases
  
  enum FetchProjects
  {
    struct Request
    {
    }
    struct Response
    {
        var projects: [Project]
        var doSelect: Bool
    }
    struct ViewModel
    {
        
        var projects: [Project]
        var doSelect: Bool
        
    }
  }
}
