//
//  ListProjectsPresenter.swift
//  ContractorApp
//
//  Created by Zaizen Kaegyoshi on 10/25/17.
//  Copyright (c) 2017 Team5. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListProjectsPresentationLogic
{
    func presentProjects(response: ListProjects.FetchProjects.Response)
}

class ListProjectsPresenter: ListProjectsPresentationLogic
{
    weak var viewController: ListProjectsDisplayLogic?
    
    // MARK: Do something
    
    func presentProjects(response: ListProjects.FetchProjects.Response) {
        self.viewController?.displayProjects(viewModel: ListProjects.FetchProjects.ViewModel(projects: response.projects, doSelect: response.doSelect))
    }
}
